spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-34-235-157-88.compute-1.amazonaws.com:8761/eureka/,http://ec2-34-235-157-88.compute-1.amazonaws.com:8861/eureka/

zuul:
  routes:
    api-v1:
      path: /api/v1/**
      serviceId: juju-web-oinp-user-feign