spring:
  application:
    name: juju-oinp-user
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwert

mybatis:
  type-aliases-package: net.dataoriented.juju.onipuser.entity
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-34-235-157-88.compute-1.amazonaws.com:8761/eureka/, http://ec2-34-235-157-88.compute-1.amazonaws.com:8861/eureka/
