spring:
  application:
    name: juju-oinp-user
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwert
server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/