spring:
  application:
    name: juju-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: http://ec2-34-235-157-88.compute-1.amazonaws.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://${eureka.instance.hostname}:8861/eureka/